name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-slim
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Print Hello
        run: echo "Hello Bro!"
  second-job:
    runs-on: ubuntu-slim
    steps:
      - name: Print greeting
        run: echo "Hello Second Job"

